services:
    postgres:
        image: postgres:15
        container_name: local_postgres
        environment:
            POSTGRES_DB: tennis_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password123
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 30s
            timeout: 10s
            retries: 5

    mongodb:
        build:
            context: .
            dockerfile: Dockerfile.mongo
        container_name: local_mongodb
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password123
            MONGO_INITDB_DATABASE: tennis_db
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
            interval: 30s
            timeout: 10s
            retries: 5

    # Optional: pgAdmin for PostgreSQL management
    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: local_pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin123
        ports:
            - "8080:80"
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        depends_on:
            - postgres
        restart: unless-stopped

    # Optional: Mongo Express for MongoDB management
    mongo-express:
        image: mongo-express:latest
        container_name: local_mongo_express
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: password123
            ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: admin123
        ports:
            - "8081:8081"
        depends_on:
            - mongodb
        restart: unless-stopped

volumes:
    postgres_data:
    mongodb_data:
    pgadmin_data:
